# Generated by Django 5.0 on 2024-03-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tic_tac_toe', '0002_game_move'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='tic_tac_toe_game',
        ),
    ]
